name: tinyllm
channels:
  - defaults
dependencies:
  - python==3.10.13
  - pip
  - pip:
      - black
      - isort
      - jieba
      - numpy==1.23.5
      - pandas
      - pytest==7.4.0
      - scikit-learn==1.3.0
      - sentencepiece==0.1.99
      - tensorboard==2.16.2
      - ./whl/torch-2.0.1+cu118-cp310-cp310-win_amd64.whl
      - transformers==4.33.2
      - tqdm
      - Requests==2.31.0
      - -i https://pypi.tuna.tsinghua.edu.cn/simple
